### ISSUE TITLE
index.html is replicated in .meta

### ISSUE THREAD

**Issue by theRealImy** [solid/solidos#129]
I noticed Since last week my storage is not displayed anymore and the console throws the cryptic message: 
```
cannot load container Error: Web error: 500 (Internal Server Error) on GET of <https://timea.solidcommunity.net/>
    value https://timea.solidcommunity.net/mashlib.min.js:50
```

What I did before: I added in my profile second storage by editing the .ttl profile file. Afterward, my original storage didn't display anymore. I deleted the additional tripe (storage) and my storage is still not displayed. 

This is on mashlib version pre 1.7.18 (pre authn move refactoring)

<img width="910" alt="image" src="https://user-images.githubusercontent.com/4144203/156795693-973e51f8-883c-43a8-a115-338acfee001a.png">

**Comment by theRealImy** [comment]
The error message in the console might not be related. I see this error a lot actually... need to investigate.

**Comment by bourgeoa** [comment]
@theRealImy You are back with the terrible !!!! podRoot/.meta that has been corrupted.

As you are the only one using dokieli as first page index.html **and** nearly the only one to encounter this problem I think they may well be related.

**Comment by bourgeoa** [comment]
I think I have a clue to where the problem arise in NSS. And it should related to DOKIELI.
DOKIELI is not only using index.html but is also doing versioning. For versioning it uses a structure ;
folder --> index.html, versions.html (I do not remind exactly) (you can see it if you use the dokieli app https://dokie.li

NSS treats all resource ending with / has container and when we introduced creation of folder with PUT we considered there was norisk of conflicting with old apps and did not check the resource property (isContainer)

Well in some situation podRoot/ is of type isContainer = false (this is  a wrong combination). NSS tries to map the container to the filesystem with as hack podRoot/.meta. NSS make a PUT to podRoot/.meta in place of podRoot/index.html has expected by Dokieli.

I think the issue is in Dokieli that should PUT to podRoot/index.html and not podRoot/ (expecting Solid server to return podRoot/index.html

Well to make it short for NSS. I should error 500 on url ending with `/` and of type `isContainer`
This is spec compliant. May be not for 500 (?)
Side effect this may block updates in dokieli in some situation.

**Comment by bourgeoa** [comment]
In mashlib/dokieli pane something shall be done to not send url ending with `/` of type `isContainer = false`

**Comment by bourgeoa** [comment]
https://github.com/solid/node-solid-server/pull/1677
