### ISSUE TITLE
Publish solid-auth-client and solid-client-authn versions

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/solidos#18]
@timbl suggested to publish a build of the solid-client-authn branch.

This could either be part of the same npm package,
or could be published with a different tag on npm.

Or just as a build somewhere.

**Comment by jaxoncreed** [comment]
I'm sorry I don't understand what this is saying. Is solid-client-authn not already published? https://www.npmjs.com/package/@inrupt/solid-client-authn-browser

**Comment by RubenVerborgh** [comment]
Woops, lemme rewind 🙂
I’m looking for a solidos release that has solid-client-authn-browser as a dependency instead of solid-auth-client. I heard there was a branch for that, but not merged given the page refresh issue.

**Comment by jaxoncreed** [comment]
Ah yep. That's this here: https://github.com/solid/node-solid-server/pull/1488 (note that it's split between 4 repos)

However, it should also be noted that this is not merged in because it would mean the user is logged out whenever they refresh. This was unacceptable from the UX perspective. These changes are also behind master.

The plan is to update the changes to master and merge it in once solid-client-authn is fixed to maintain the session between refreshes.

**Comment by RubenVerborgh** [comment]
Exactly; so the purpose of this issue is to suggest releasing it anyway; but not as a main release, but rather as a tagged release on npm.

**Comment by jaxoncreed** [comment]
Okay, I'll need to ask @emmettownsend  about this. It would take extra work to get these ready for a full release. I am currently committed to the CSS IdP, so I'll see what he prioritizes.

**Comment by angelo-v** [comment]
I guess this is a requirement to run SolidOS on CSS?

**Comment by RubenVerborgh** [comment]
Thanks @jaxoncreed. For CSS, we mainly want to test, which we can do by using a mock auth module on the server.
