### ISSUE TITLE
Container or index.html choice should be a split screen

### ISSUE THREAD

**Issue by sideshowtom** [solid/solidos#30]
@DoctorBud described this in the SolidOS chat at https://gitter.im/solid/solidos?at=600b8db236db01248a96f48e

**Comment by DoctorBud** [comment]
If I create an `/index.html` in the root of my POD, then that enables me to create a custom landing page experience. For example, SolidOS has such an example:
     https://solidos.solidcommunity.net

However, the presence of this file inhibits the ability for the root to be seen as a 'container', which means that the ordinary 'Your Storage' feature won't show anything other than a green Plus sign. The contents of the root container will not be shown in the databrowser's outliner.

My assumption is that the DataBrowser doesn't force the `Accept: text/turtle` header to the `GET /` request, so that NSS returns a convenient default (either text/html or text/turtle, depending on the existence of an `/index.html`). So that you cannot use the DataBrowser to view the container in the outline view.

NSS supports the ability to have an `/index.html` at the root and still be structured as a container; but this ability is not utilized properly by the databrowser. For example, the following request returns the proper turtle description of the container and its contents, even when `/index.html` is present.
    `curl -H "Accept: text/turtle"  https://solidos.solidcommunity.net`

Fixes needed:
- The 'Your Storage` tab should always show an outliner view of the container heirarchy.
- Any outliner view that shows an `index.html` in the containment tree (e.g., `/public/foo/index.html` should also allow that container (e.g.,`/public/foo/`) to be viewed AS a container  in the outline view, and alternatively should render the `index.html` as HTML. @sideshowtom suggested a split screen when creating this Issue, but the ability to toggle between views would be sufficient and better use of the screen real estate.

**Comment by sideshowtom** [comment]
One thing that occurs to me is what if you take the index.html choice and follow a few links in there and then decide you really wanted the outline view, could you get back to that easily.  Just $0.02

**Comment by mikeadams1** [comment]
@DoctorBud I’m not sure which version of mashlib your using but, Maybe you should check this view out, https://portal.inrupt.net/?uri=https%3A%2F%2Fsolidos.solidcommunity.net%2F Here I can see all the files in the root container.

**Comment by theRealImy** [comment]
fixed
