### ISSUE TITLE
Auth-Upgrade cookie/session problem

### ISSUE THREAD

**Issue by theRealImy** [solid/solidos#58]
While testing on solidcommunity.net:8443 with NSS and mashlib@1.7.5-alpha-3-98ed3958 deployed 13.09.21.
It is not a session expiration issue because the problem only occurs on certain activities (clicking on resources) in the pod while logged in.
Cannot reproduce in a consistent manner it appear at random, at first evaluation. 
What happens:
* on is logged in to the pod and creates resources (any: address book, document...)
* when clicking around from resource to resource at some point the use is logged out
* when tempting to login again the following appears:
 URL: https://solidcommunity.net:8443/authorize?response_type=code&display=&scope=openid%20offline_access&client_id=aab7c97504383537d09cce3b50a6947a&redirect_uri=https%3A%2F%2Ftimeatest.solidcommunity.net%3A8443%2Fpublic%2F&state=0b9db4e5d05441b1a1073f99bfdb2f76&nonce=&request=
 
![Screenshot 2021-09-14 at 12 11 15](https://user-images.githubusercontent.com/4144203/133239258-3bb441db-047a-4723-8e82-c4ef8c92c355.png)
and I cannot login anaymore at all (Same issue appears). 
Solution that works: logout on the server page and then login again.
![Screenshot 2021-09-14 at 12 12 50](https://user-images.githubusercontent.com/4144203/133239542-29b5f650-5450-4535-8086-466dedc26250.png)

**Comment by jeff-zucker** [comment]
> when clicking around from resource to resource at some point the use is logged out

This is the problem, not what happens later when you try to login a second time.  This logging out should not be happening so we should not focus on what occurs after it happens but on preventing it from happening.  My first question is - how do you know you have been logged out?  Because the error you show on logging back in is an error from a duplicate login so my guess is that you were not really logged out but that the UI thought you were logged out.   Is there a login button?  Are your pane-icons the full set you get when you login?  Can you create, edit, or delete a resource?  Each of these aspects of logging out is different so it is important to notice if they are all occurring or only one.

**Comment by theRealImy** [comment]
For now, with the latest auth-upgrade changes, I cannot seem to reproduce this behavior. I will keep an eye.

**Comment by bourgeoa** [comment]
Solved as from beta
